name: linux-release

on: workflow_dispatch

env:
  SOURCE_DIR: ${{ github.workspace }}
  QT_VERSION: 5.15.2

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '${{ env.QT_VERSION }}'
          target: 'desktop'
          install-deps: 'true'
          modules: 'qtscript'

      - name: Versions
        run: qmake -v

      - name: Build
        run: |
          cd emulator
          qmake "CONFIG+=release" -r GST_VERSION=1.0 QtUkncBtl.pro
          make

      - name: Packaging
        working-directory: ${{ env.SOURCE_DIR }}/emulator
        run: |
          export PATH=$HOME/Qt/5.15/clang_64/bin:$PATH
          mv QtUkncBtl QtUkncBtl.app
          macdeployqt QtUkncBtl.app -verbose=1 -dmg
          mv QtUkncBtl.dmg QtUkncBtl-macOS-${{ github.run_id }}.dmg
          ls -l *.dmg

      - name: Linux artefact
        uses: actions/upload-artifact@v3
        with:
          name: AppImage
          path: ${{ env.SOURCE_DIR }}/emulator/*.dmg
