name: push-ubuntu

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        qt-version: ['5.9.9', '5.10.1', '5.11.3', '5.12.11', '5.13.2', '5.14.2', '5.15.2']

    steps:
    - uses: actions/checkout@v3

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{ matrix.qt-version }}
        install-deps: 'true'
        modules: 'qtscript'
    
    - name: Versions
      run: qmake -v

    - name: Build
      run: |
        qmake "CONFIG+=debug" QtUkncBtl.pro
        make
        
